### ISSUE TITLE
Failed to get user domain

### ISSUE THREAD

**Issue by Jellyfishxoxo** [thecodrr/nimbus-note-exporter#1]
Hi, 

I am trying to use the tool in Kali(Debian) but during the login it throws an error: Failed to get user domain.
I edited the auth.js to get more info and found out it receives the code 401.
See the error here:

```
⠸ Logging you in...Response status: 401
/usr/local/lib/node_modules/nimbus-note-exporter/dist/api/auth.js:58
            throw new Error("Failed to get user domain.");
                  ^

Error: Failed to get user domain.
    at /usr/local/lib/node_modules/nimbus-note-exporter/dist/api/auth.js:58:19
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/nimbus-note-exporter/dist/api/auth.js:23:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.13.0
```

The credentials are correct as I double checked it.
When I try to log in using: 
`curl -I -b "eversessionid=<your-session-id>" https://nimbusweb.me/client?t=regfsour:header`
I get the response:
```
HTTP/2 302 
content-type: text/plain; charset=utf-8
content-length: 74
date: Wed, 01 Nov 2023 09:22:36 GMT
x-powered-by: Express
location: //petrik-notes.nimbusweb.me/client?t=regfsour:header
vary: Accept
strict-transport-security: max-age=15724800; includeSubDomains
x-cache: Miss from cloudfront
via: 1.1 8bb90d44758ce70476efdf577c8bd268.cloudfront.net (CloudFront)
x-amz-cf-pop: AMS58-P5
x-amz-cf-id: AaL_rYb7xNa2F27v1VwTRTIxWKN8cShODBJl2PsdWy1TlL7MBGnRfw==
```
So I tried to edit the code to follow redirect but no luck.
I have also tried to hardcode the session ID but I get same error.

Do you have any idea what could be wrong or if there is small tune required in the code?
I guess nimbus probably changed something with URLs but I am not sure.

Thank you,

**Comment by thecodrr** [comment]
Should be fixed.
